name: Build Documentation

on: 
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build-docs:
    name: Build documentation using Sphinx
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v3
        with:
          ref: "main"
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.4
          architecture: "x64"
      - name: Install sphinx, furo, black, and Flake8
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade sphinx furo black flake8
      - name: Run Flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Run black
        run: |
          black .
      - name: Run sphinx-build through the Makefile
        uses: actions/checkout@v3
        run: |
          make html
      - name: Push to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: docs-build/html