name: Build and Publish on PyPI

on: 
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build-ubuntu:
    name: Build and publish Python distribution
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v3
        with:
          ref: "main"
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.4
          architecture: "x64"
      - name: Install build, black, and Flake8
        run: |
            python -m pip install --upgrade pip
            pip install --upgrade build black flake8
      - name: Run Flake8
        run: |
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Run black
        run: |
            black .
      - name: Build binary wheel and a source tarball
        run: python -m build
      - name: Publish on PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}